/*
 *
 * LIMITED USE SOFTWARE LICENSE AGREEMENT
 * This Limited Use Software License Agreement (the "Agreement") is a legal agreement between you, the end-user, and the FlatstoneTech Team ("FlatstoneTech"). By downloading or purchasing the software material, which includes source code (the "Source Code"), artwork data, music and software tools (collectively, the "Software"), you are agreeing to be bound by the terms of this Agreement. If you do not agree to the terms of this Agreement, promptly destroy the Software you may have downloaded or copied.
 * FlatstoneTech SOFTWARE LICENSE
 * 1. Grant of License. FlatstoneTech grants to you the right to use the Software. You have no ownership or proprietary rights in or to the Software, or the Trademark. For purposes of this section, "use" means loading the Software into RAM, as well as installation on a hard disk or other storage device. The Software, together with any archive copy thereof, shall be destroyed when no longer used in accordance with this Agreement, or when the right to use the Software is terminated. You agree that the Software will not be shipped, transferred or exported into any country in violation of the U.S. Export Administration Act (or any other law governing such matters) and that you will not utilize, in any other manner, the Software in violation of any applicable law.
 * 2. Permitted Uses. For educational purposes only, you, the end-user, may use portions of the Source Code, such as particular routines, to develop your own software, but may not duplicate the Source Code, except as noted in paragraph 4. The limited right referenced in the preceding sentence is hereinafter referred to as "Educational Use." By so exercising the Educational Use right you shall not obtain any ownership, copyright, proprietary or other interest in or to the Source Code, or any portion of the Source Code. You may dispose of your own software in your sole discretion. With the exception of the Educational Use right, you may not otherwise use the Software, or an portion of the Software, which includes the Source Code, for commercial gain.
 * 3. Prohibited Uses: Under no circumstances shall you, the end-user, be permitted, allowed or authorized to commercially exploit the Software. Neither you nor anyone at your direction shall do any of the following acts with regard to the Software, or any portion thereof:
 * Rent;
 * Sell;
 * Lease;
 * Offer on a pay-per-play basis;
 * Distribute for money or any other consideration; or
 * In any other manner and through any medium whatsoever commercially exploit or use for any commercial purpose.
 * Notwithstanding the foregoing prohibitions, you may commercially exploit the software you develop by exercising the Educational Use right, referenced in paragraph 2. hereinabove.
 * 4. Copyright. The Software and all copyrights related thereto (including all characters and other images generated by the Software or depicted in the Software) are owned by FlatstoneTech and is protected by United States copyright laws and international treaty provisions. FlatstoneTech shall retain exclusive ownership and copyright in and to the Software and all portions of the Software and you shall have no ownership or other proprietary interest in such materials. You must treat the Software like any other copyrighted material. You may not otherwise reproduce, copy or disclose to others, in whole or in any part, the Software. You may not copy the written materials accompanying the Software. You agree to use your best efforts to see that any user of the Software licensed hereunder complies with this Agreement.
 * 5. NO WARRANTIES. FLATSTONETECH DISCLAIMS ALL WARRANTIES, BOTH EXPRESS IMPLIED, INCLUDING BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE WITH RESPECT TO THE SOFTWARE. THIS LIMITED WARRANTY GIVES YOU SPECIFIC LEGAL RIGHTS. YOU MAY HAVE OTHER RIGHTS WHICH VARY FROM JURISDICTION TO JURISDICTION. FlatstoneTech DOES NOT WARRANT THAT THE OPERATION OF THE SOFTWARE WILL BE UNINTERRUPTED, ERROR FREE OR MEET YOUR SPECIFIC REQUIREMENTS. THE WARRANTY SET FORTH ABOVE IS IN LIEU OF ALL OTHER EXPRESS WARRANTIES WHETHER ORAL OR WRITTEN. THE AGENTS, EMPLOYEES, DISTRIBUTORS, AND DEALERS OF FlatstoneTech ARE NOT AUTHORIZED TO MAKE MODIFICATIONS TO THIS WARRANTY, OR ADDITIONAL WARRANTIES ON BEHALF OF FlatstoneTech.
 * Exclusive Remedies. The Software is being offered to you free of any charge. You agree that you have no remedy against FlatstoneTech, its affiliates, contractors, suppliers, and agents for loss or damage caused by any defect or failure in the Software regardless of the form of action, whether in contract, tort, includinegligence, strict liability or otherwise, with regard to the Software. Copyright and other proprietary matters will be governed by United States laws and international treaties. IN ANY CASE, FlatstoneTech SHALL NOT BE LIABLE FOR LOSS OF DATA, LOSS OF PROFITS, LOST SAVINGS, SPECIAL, INCIDENTAL, CONSEQUENTIAL, INDIRECT OR OTHER SIMILAR DAMAGES ARISING FROM BREACH OF WARRANTY, BREACH OF CONTRACT, NEGLIGENCE, OR OTHER LEGAL THEORY EVEN IF FLATSTONETECH OR ITS AGENT HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES, OR FOR ANY CLAIM BY ANY OTHER PARTY. Some jurisdictions do not allow the exclusion or limitation of incidental or consequential damages, so the above limitation or exclusion may not apply to you.
 */

package tech.flatstone.appliedlogistics.common.grid;


import org.jgrapht.experimental.dag.DirectedAcyclicGraph;
import org.jgrapht.graph.ClassBasedEdgeFactory;
import tech.flatstone.appliedlogistics.common.util.LogHelper;

import java.util.ArrayList;
import java.util.LinkedList;
import java.util.UUID;
import java.util.concurrent.BrokenBarrierException;
import java.util.concurrent.ConcurrentLinkedQueue;
import java.util.concurrent.CyclicBarrier;

class gridServer implements Runnable {
    private DirectedAcyclicGraph<UUID, FilteredEdge> graph;
    private ConcurrentLinkedQueue<UUID> vertexQueue;
    private ConcurrentLinkedQueue<uuidPair> edgeQueue;
    private CyclicBarrier barrier;
    private LinkedList activeObjects;
    ArrayList<uuidPair> vertexMissing;

    public gridServer() {
        graph = new DirectedAcyclicGraph<UUID, FilteredEdge>(
                new ClassBasedEdgeFactory<UUID, FilteredEdge>(FilteredEdge.class)
        );

        vertexQueue = new ConcurrentLinkedQueue<UUID>();
        edgeQueue = new ConcurrentLinkedQueue<uuidPair>();
        activeObjects = new LinkedList();

        if (vertexQueue == null)
            throw new NullPointerException();

        if (edgeQueue == null)
            throw new NullPointerException();

        barrier = new CyclicBarrier(2);

        vertexMissing = new ArrayList<uuidPair>();
    }

    @Override
    public void run() {
        //sync with world server
        try {
            barrier.await();
        } catch (InterruptedException e) {
            LogHelper.fatal(e.getLocalizedMessage());
            e.printStackTrace();
        } catch (BrokenBarrierException e) {
            LogHelper.fatal(e.getLocalizedMessage());
            e.printStackTrace();
        }

        //step the transport simulation
        this.gridTick();
    }

    /**
     * this method is called from the games main server thread in the server tick handler
     */
    public void sync() {
        try {
            barrier.await();
        } catch (InterruptedException e) {
            LogHelper.fatal(e.getLocalizedMessage());
            e.printStackTrace();
        } catch (BrokenBarrierException e) {
            LogHelper.fatal(e.getLocalizedMessage());
            e.printStackTrace();
        }
    }

    private void gridTick() {

        //ingest vertex queue
        for (UUID id : vertexQueue) {
            graph.addVertex(id);
        }

        //handle a hopefully rare situation where a vertex and edge are added between ingest vertex and ingest edge
        if (!vertexMissing.isEmpty()) {
            edgeQueue.addAll(vertexMissing);
            vertexMissing.clear();
        }

        //ingest edge queue
        for (uuidPair pair : edgeQueue) {
            if ((graph.containsVertex(pair.getUuid1())) && (graph.containsVertex(pair.getUuid2()))) {
                graph.addEdge(pair.getUuid1(), pair.getUuid2());
            } else {
                vertexMissing.add(pair);
                LogHelper.debug("A vertex for edge:" + pair.getUuid1() + " -> " + pair.getUuid2() + " does not exist");
            }
        }



        //update grid objects
        //ingest new objects
    }

    boolean addVertex(UUID uuid) {
        return uuid != null && vertexQueue.offer(uuid);
    }

    boolean addEdge(UUID source, UUID destination) {
        return !((source == null) || (destination == null)) && edgeQueue.offer(new uuidPair(source, destination));
    }

    FilteredEdge getEdge(UUID source, UUID destination) {
        return graph.getEdge(source, destination);
    }
}
