/*
 * LIMITED USE SOFTWARE LICENSE AGREEMENT
 * This Limited Use Software License Agreement (the "Agreement") is a legal agreement between you, the end-user, and the FlatstoneTech Team ("FlatstoneTech"). By downloading or purchasing the software material, which includes source code (the "Source Code"), artwork data, music and software tools (collectively, the "Software"), you are agreeing to be bound by the terms of this Agreement. If you do not agree to the terms of this Agreement, promptly destroy the Software you may have downloaded or copied.
 * FlatstoneTech SOFTWARE LICENSE
 * 1. Grant of License. FlatstoneTech grants to you the right to use the Software. You have no ownership or proprietary rights in or to the Software, or the Trademark. For purposes of this section, "use" means loading the Software into RAM, as well as installation on a hard disk or other storage device. The Software, together with any archive copy thereof, shall be destroyed when no longer used in accordance with this Agreement, or when the right to use the Software is terminated. You agree that the Software will not be shipped, transferred or exported into any country in violation of the U.S. Export Administration Act (or any other law governing such matters) and that you will not utilize, in any other manner, the Software in violation of any applicable law.
 * 2. Permitted Uses. For educational purposes only, you, the end-user, may use portions of the Source Code, such as particular routines, to develop your own software, but may not duplicate the Source Code, except as noted in paragraph 4. The limited right referenced in the preceding sentence is hereinafter referred to as "Educational Use." By so exercising the Educational Use right you shall not obtain any ownership, copyright, proprietary or other interest in or to the Source Code, or any portion of the Source Code. You may dispose of your own software in your sole discretion. With the exception of the Educational Use right, you may not otherwise use the Software, or an portion of the Software, which includes the Source Code, for commercial gain.
 * 3. Prohibited Uses: Under no circumstances shall you, the end-user, be permitted, allowed or authorized to commercially exploit the Software. Neither you nor anyone at your direction shall do any of the following acts with regard to the Software, or any portion thereof:
 *  * Rent;
 *  * Sell;
 *  * Lease;
 *  * Offer on a pay-per-play basis;
 *  * Distribute for money or any other consideration; or
 *  * In any other manner and through any medium whatsoever commercially exploit or use for any commercial purpose.
 *  * Notwithstanding the foregoing prohibitions, you may commercially exploit the software you develop by exercising the Educational Use right, referenced in paragraph 2. hereinabove.
 *  4. Copyright. The Software and all copyrights related thereto (including all characters and other images generated by the Software or depicted in the Software) are owned by FlatstoneTech and is protected by United States copyright laws and international treaty provisions. FlatstoneTech shall retain exclusive ownership and copyright in and to the Software and all portions of the Software and you shall have no ownership or other proprietary interest in such materials. You must treat the Software like any other copyrighted material. You may not otherwise reproduce, copy or disclose to others, in whole or in any part, the Software. You may not copy the written materials accompanying the Software. You agree to use your best efforts to see that any user of the Software licensed hereunder complies with this Agreement.
 *  5. NO WARRANTIES. FLATSTONETECH DISCLAIMS ALL WARRANTIES, BOTH EXPRESS IMPLIED, INCLUDING BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE WITH RESPECT TO THE SOFTWARE. THIS LIMITED WARRANTY GIVES YOU SPECIFIC LEGAL RIGHTS. YOU MAY HAVE OTHER RIGHTS WHICH VARY FROM JURISDICTION TO JURISDICTION. FlatstoneTech DOES NOT WARRANT THAT THE OPERATION OF THE SOFTWARE WILL BE UNINTERRUPTED, ERROR FREE OR MEET YOUR SPECIFIC REQUIREMENTS. THE WARRANTY SET FORTH ABOVE IS IN LIEU OF ALL OTHER EXPRESS WARRANTIES WHETHER ORAL OR WRITTEN. THE AGENTS, EMPLOYEES, DISTRIBUTORS, AND DEALERS OF FlatstoneTech ARE NOT AUTHORIZED TO MAKE MODIFICATIONS TO THIS WARRANTY, OR ADDITIONAL WARRANTIES ON BEHALF OF FlatstoneTech.
 *  Exclusive Remedies. The Software is being offered to you free of any charge. You agree that you have no remedy against FlatstoneTech, its affiliates, contractors, suppliers, and agents for loss or damage caused by any defect or failure in the Software regardless of the form of action, whether in contract, tort, includinegligence, strict liability or otherwise, with regard to the Software. Copyright and other proprietary matters will be governed by United States laws and international treaties. IN ANY CASE, FlatstoneTech SHALL NOT BE LIABLE FOR LOSS OF DATA, LOSS OF PROFITS, LOST SAVINGS, SPECIAL, INCIDENTAL, CONSEQUENTIAL, INDIRECT OR OTHER SIMILAR DAMAGES ARISING FROM BREACH OF WARRANTY, BREACH OF CONTRACT, NEGLIGENCE, OR OTHER LEGAL THEORY EVEN IF FLATSTONETECH OR ITS AGENT HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES, OR FOR ANY CLAIM BY ANY OTHER PARTY. Some jurisdictions do not allow the exclusion or limitation of incidental or consequential damages, so the above limitation or exclusion may not apply to you.
 */

package tech.flatstone.appliedlogistics.common.config;

import net.minecraftforge.common.config.Configuration;
import tech.flatstone.appliedlogistics.api.features.EnumOreType;
import tech.flatstone.appliedlogistics.common.util.ConfigHelper;
import tech.flatstone.appliedlogistics.common.util.EnumOres;

import java.util.EnumMap;
import java.util.Map;

public class ConfigWorldGen {
    private static final Map<EnumOres, OreConfig> OreWorldGen = new EnumMap<>(EnumOres.class);
    private static final Map<EnumOres, OreConfig> OreWorldGenDefaults = new EnumMap<>(EnumOres.class);
    private static final int[] DEFAULT_DIMENSION_BLACKLIST = {-1, 1};

    static {
        // Initialize defaults
        for (EnumOres ore : EnumOres.byType(EnumOreType.ORE)) {
            OreConfig defaultConfig = new OreConfig();
            defaultConfig.Enabled = true;
            defaultConfig.DimensionRestriction = RestrictionType.BLACKLIST;
            defaultConfig.Dimensions = DEFAULT_DIMENSION_BLACKLIST;

            // Might want to vary this per-ore at some point, but so far it's constant
            defaultConfig.ChunkOccurrence = 20;

            switch (ore) {
                case COPPER:
                    defaultConfig.MinY = 10;
                    defaultConfig.MaxY = 75;
                    defaultConfig.VeinSize = 16;
                    defaultConfig.Weight = 40;
                    break;

                case TIN:
                    defaultConfig.MinY = 20;
                    defaultConfig.MaxY = 55;
                    defaultConfig.VeinSize = 10;
                    defaultConfig.Weight = 40;
                    break;

                case SILVER:
                    defaultConfig.MinY = 5;
                    defaultConfig.MaxY = 30;
                    defaultConfig.VeinSize = 8;
                    defaultConfig.Weight = 20;
                    break;

                case LEAD:
                    defaultConfig.MinY = 10;
                    defaultConfig.MaxY = 35;
                    defaultConfig.VeinSize = 8;
                    defaultConfig.Weight = 20;
                    break;

                case NICKEL:
                    defaultConfig.MinY = 5;
                    defaultConfig.MaxY = 60;
                    defaultConfig.VeinSize = 4;
                    defaultConfig.Weight = 20;
                    break;

                case RUTILE:
                    defaultConfig.MinY = 1;
                    defaultConfig.MaxY = 75;
                    defaultConfig.VeinSize = 20;
                    defaultConfig.Weight = 30;
                    break;
            }

            OreWorldGenDefaults.put(ore, defaultConfig);
        }
    }

    public static Map<EnumOres, OreConfig> getOreWorldGen() {
        return OreWorldGen;
    }

    public static void init(Configuration configuration) {
        configuration.setCategoryLanguageKey(Config.CONFIG_WORLDGEN, "config.worldGen");
        configuration.setCategoryRequiresWorldRestart(Config.CONFIG_WORLDGEN, false);

        final String WORLDGEN_ORES = String.format("%s.%s", Config.CONFIG_WORLDGEN, "ores");

        final String DESC_ENABLED = "Enable %s in world generation";
        final String DESC_MIN_Y = "Minimum Y-level that %s will spawn at";
        final String DESC_MAX_Y = "Maximum Y-level that %s will spawn at";
        final String DESC_VEIN_SIZE = "Size of %s veins";
        final String DESC_WEIGHT = "Percent chance that %s will generate for each chunk occurrence";
        final String DESC_CHUNK_OCCURRENCE = "Number of times that %s will attempt to generate in each chunk";
        final String DESC_DIM_RESTRICTION = "Either 'blacklist' or 'whitelist'";
        final String DESC_DIM_LIST = "Dimension numbers for restriction";

        for (EnumOres ore : EnumOres.byType(EnumOreType.ORE)) {
            String oreName = ore.getName();
            String oreLower = oreName.toLowerCase();
            String category = String.format("%s.%s", WORLDGEN_ORES, oreName);
            OreConfig defaultConfig = OreWorldGenDefaults.get(ore);

            OreConfig oreConfig;
            if (OreWorldGen.containsKey(ore)) {
                // Manipulating the existing config will automatically update WorldGen
                oreConfig = OreWorldGen.get(ore);
            } else {
                oreConfig = new OreConfig();
            }

            oreConfig.Enabled = ConfigHelper.getBoolean(configuration, oreName, WORLDGEN_ORES, defaultConfig.Enabled, String.format(DESC_ENABLED, oreLower));

            oreConfig.MinY = ConfigHelper.getInteger(configuration, "Min Height", category, defaultConfig.MinY, String.format(DESC_MIN_Y, oreLower));
            oreConfig.MaxY = ConfigHelper.getInteger(configuration, "Max Height", category, defaultConfig.MaxY, String.format(DESC_MAX_Y, oreLower));
            oreConfig.VeinSize = ConfigHelper.getInteger(configuration, "Vein Size", category, defaultConfig.VeinSize, String.format(DESC_VEIN_SIZE, oreLower));
            oreConfig.Weight = ConfigHelper.getInteger(configuration, "Weight", category, defaultConfig.Weight, String.format(DESC_WEIGHT, oreLower));
            oreConfig.ChunkOccurrence = ConfigHelper.getInteger(configuration, "Chunk Occurrence", category, defaultConfig.ChunkOccurrence, String.format(DESC_CHUNK_OCCURRENCE, oreLower));

            String defaultDimRestriction = defaultConfig.DimensionRestriction.name().toLowerCase();
            String dimRestriction = ConfigHelper.getString(configuration, "Dimension Restriction", category, defaultDimRestriction, DESC_DIM_RESTRICTION);
            oreConfig.DimensionRestriction = RestrictionType.fromString(dimRestriction, defaultConfig.DimensionRestriction);

            oreConfig.Dimensions = ConfigHelper.getIntegerList(configuration, "Dimensions", category, defaultConfig.Dimensions, DESC_DIM_LIST);

            OreWorldGen.put(ore, oreConfig);
        }
    }

    public enum RestrictionType {
        BLACKLIST,
        WHITELIST;

        public static RestrictionType fromString(String str, RestrictionType def) {
            for (RestrictionType rt : values()) {
                if (rt.name().equalsIgnoreCase(str)) {
                    return rt;
                }
            }

            return def;
        }
    }

    public static class OreConfig {
        public boolean Enabled;
        public int MinY;
        public int MaxY;
        public int VeinSize;
        public int Weight;
        public int ChunkOccurrence;
        public RestrictionType DimensionRestriction;
        public int[] Dimensions;

        public boolean isEnabledForDim(int dim) {
            boolean inList = false;
            for (int listDim : Dimensions)
                inList = inList || listDim == dim;
            return (inList && DimensionRestriction == RestrictionType.WHITELIST) ||
                    (!inList && DimensionRestriction == RestrictionType.BLACKLIST);
        }
    }
}
