/*
 *
 * LIMITED USE SOFTWARE LICENSE AGREEMENT
 * This Limited Use Software License Agreement (the "Agreement") is a legal agreement between you, the end-user, and the FlatstoneTech Team ("FlatstoneTech"). By downloading or purchasing the software material, which includes source code (the "Source Code"), artwork data, music and software tools (collectively, the "Software"), you are agreeing to be bound by the terms of this Agreement. If you do not agree to the terms of this Agreement, promptly destroy the Software you may have downloaded or copied.
 * FlatstoneTech SOFTWARE LICENSE
 * 1. Grant of License. FlatstoneTech grants to you the right to use the Software. You have no ownership or proprietary rights in or to the Software, or the Trademark. For purposes of this section, "use" means loading the Software into RAM, as well as installation on a hard disk or other storage device. The Software, together with any archive copy thereof, shall be destroyed when no longer used in accordance with this Agreement, or when the right to use the Software is terminated. You agree that the Software will not be shipped, transferred or exported into any country in violation of the U.S. Export Administration Act (or any other law governing such matters) and that you will not utilize, in any other manner, the Software in violation of any applicable law.
 * 2. Permitted Uses. For educational purposes only, you, the end-user, may use portions of the Source Code, such as particular routines, to develop your own software, but may not duplicate the Source Code, except as noted in paragraph 4. The limited right referenced in the preceding sentence is hereinafter referred to as "Educational Use." By so exercising the Educational Use right you shall not obtain any ownership, copyright, proprietary or other interest in or to the Source Code, or any portion of the Source Code. You may dispose of your own software in your sole discretion. With the exception of the Educational Use right, you may not otherwise use the Software, or an portion of the Software, which includes the Source Code, for commercial gain.
 * 3. Prohibited Uses: Under no circumstances shall you, the end-user, be permitted, allowed or authorized to commercially exploit the Software. Neither you nor anyone at your direction shall do any of the following acts with regard to the Software, or any portion thereof:
 * Rent;
 * Sell;
 * Lease;
 * Offer on a pay-per-play basis;
 * Distribute for money or any other consideration; or
 * In any other manner and through any medium whatsoever commercially exploit or use for any commercial purpose.
 * Notwithstanding the foregoing prohibitions, you may commercially exploit the software you develop by exercising the Educational Use right, referenced in paragraph 2. hereinabove.
 * 4. Copyright. The Software and all copyrights related thereto (including all characters and other images generated by the Software or depicted in the Software) are owned by FlatstoneTech and is protected by United States copyright laws and international treaty provisions. FlatstoneTech shall retain exclusive ownership and copyright in and to the Software and all portions of the Software and you shall have no ownership or other proprietary interest in such materials. You must treat the Software like any other copyrighted material. You may not otherwise reproduce, copy or disclose to others, in whole or in any part, the Software. You may not copy the written materials accompanying the Software. You agree to use your best efforts to see that any user of the Software licensed hereunder complies with this Agreement.
 * 5. NO WARRANTIES. FLATSTONETECH DISCLAIMS ALL WARRANTIES, BOTH EXPRESS IMPLIED, INCLUDING BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE WITH RESPECT TO THE SOFTWARE. THIS LIMITED WARRANTY GIVES YOU SPECIFIC LEGAL RIGHTS. YOU MAY HAVE OTHER RIGHTS WHICH VARY FROM JURISDICTION TO JURISDICTION. FlatstoneTech DOES NOT WARRANT THAT THE OPERATION OF THE SOFTWARE WILL BE UNINTERRUPTED, ERROR FREE OR MEET YOUR SPECIFIC REQUIREMENTS. THE WARRANTY SET FORTH ABOVE IS IN LIEU OF ALL OTHER EXPRESS WARRANTIES WHETHER ORAL OR WRITTEN. THE AGENTS, EMPLOYEES, DISTRIBUTORS, AND DEALERS OF FlatstoneTech ARE NOT AUTHORIZED TO MAKE MODIFICATIONS TO THIS WARRANTY, OR ADDITIONAL WARRANTIES ON BEHALF OF FlatstoneTech.
 * Exclusive Remedies. The Software is being offered to you free of any charge. You agree that you have no remedy against FlatstoneTech, its affiliates, contractors, suppliers, and agents for loss or damage caused by any defect or failure in the Software regardless of the form of action, whether in contract, tort, includinegligence, strict liability or otherwise, with regard to the Software. Copyright and other proprietary matters will be governed by United States laws and international treaties. IN ANY CASE, FlatstoneTech SHALL NOT BE LIABLE FOR LOSS OF DATA, LOSS OF PROFITS, LOST SAVINGS, SPECIAL, INCIDENTAL, CONSEQUENTIAL, INDIRECT OR OTHER SIMILAR DAMAGES ARISING FROM BREACH OF WARRANTY, BREACH OF CONTRACT, NEGLIGENCE, OR OTHER LEGAL THEORY EVEN IF FLATSTONETECH OR ITS AGENT HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES, OR FOR ANY CLAIM BY ANY OTHER PARTY. Some jurisdictions do not allow the exclusion or limitation of incidental or consequential damages, so the above limitation or exclusion may not apply to you.
 */

package tech.flatstone.appliedlogistics.client.util;

import net.minecraft.client.renderer.block.model.BakedQuad;
import net.minecraft.client.renderer.block.model.ItemCameraTransforms;
import net.minecraft.client.renderer.texture.TextureAtlasSprite;
import net.minecraft.client.renderer.vertex.DefaultVertexFormats;
import net.minecraft.client.renderer.vertex.VertexFormat;
import net.minecraft.client.renderer.vertex.VertexFormatElement;
import net.minecraft.client.renderer.vertex.VertexFormatElement.EnumType;
import net.minecraft.client.renderer.vertex.VertexFormatElement.EnumUsage;
import net.minecraft.client.resources.model.IBakedModel;
import net.minecraft.util.EnumFacing;
import net.minecraftforge.client.model.IColoredBakedQuad;
import net.minecraftforge.client.model.IFlexibleBakedModel;
import net.minecraftforge.client.model.pipeline.LightUtil;
import net.minecraftforge.client.model.pipeline.UnpackedBakedQuad;
import net.minecraftforge.fml.relauncher.ReflectionHelper;

import javax.vecmath.Vector3f;
import java.lang.reflect.Field;
import java.util.ArrayList;
import java.util.List;
import java.util.WeakHashMap;

@SuppressWarnings({"deprecation", "unchecked"})
public class ModelTransformer {

    public static IBakedModel transform(IBakedModel model, IVertexTransformer transformer, VertexFormat format) {

        return transform(model, transformer, IVertexFormatTransformer.NONE, format);
    }

    public static IBakedModel transform(IBakedModel model, IVertexTransformer transformer, IVertexFormatTransformer vfTransformer,
                                        VertexFormat original) {

        VertexFormat newFormat = vfTransformer.getNewFormat(original);
        List<BakedQuad>[] quads = new List[7];
        for (int i = 0; i < quads.length; i++) {
            quads[i] = new ArrayList<BakedQuad>();
            for (BakedQuad quad : (i == 6 ? model.getGeneralQuads() : model.getFaceQuads(EnumFacing.getFront(i))))
                quads[i].add(transform(quad, transformer, vfTransformer, original, newFormat));
        }
        return new TransformedModel(model, quads, newFormat);
    }

    private static BakedQuad transform(BakedQuad quad, IVertexTransformer transformer, IVertexFormatTransformer vfTransformer,
                                       final VertexFormat original, final VertexFormat format) {

        // TODO: Optimize
        Field f = ReflectionHelper.findField(UnpackedBakedQuad.class, "unpackedData");
        f.setAccessible(true);
        UnpackedBakedQuad.Builder builder = new UnpackedBakedQuad.Builder(format);
        if (quad.hasTintIndex()) builder.setQuadTint(quad.getTintIndex());
        if (quad instanceof IColoredBakedQuad) builder.setQuadColored();
        builder.setQuadOrientation(quad.getFace());
        LightUtil.putBakedQuad(builder, quad);
        UnpackedBakedQuad unpackedQuad = builder.build();
        try {
            float[][][] unpackedData = (float[][][]) f.get(unpackedQuad);
            int count = format.getElementCount();
            for (int v = 0; v < 4; v++) {
                for (int e = 0; e < count; e++) {
                    VertexFormatElement element = format.getElement(e);
                    unpackedData[v][e] = transformer.transform(element.getType(), element.getUsage(), unpackedData[v][e]);
                }
            }
            vfTransformer.remap(original, unpackedData);
        } catch (Exception e) {
            e.printStackTrace();
        }
        return unpackedQuad;
    }

    public static interface IVertexTransformer {

        public float[] transform(EnumType type, EnumUsage usage, float... data);

    }

    public static interface IVertexFormatTransformer {

        public static final IVertexFormatTransformer NONE = new IVertexFormatTransformer() {

            @Override
            public VertexFormat getNewFormat(VertexFormat original) {

                return original;
            }

            @Override
            public float[][][] remap(VertexFormat original, float[][][] data) {

                return data;
            }

        };

        public static final IVertexFormatTransformer COMPUTE_NORMALS = new IVertexFormatTransformer() {

            private final WeakHashMap<VertexFormat, VertexFormat> formats = new WeakHashMap<VertexFormat, VertexFormat>();

            @Override
            public VertexFormat getNewFormat(VertexFormat original) {

                if (original.hasColor()) return original;
                VertexFormat format = formats.get(original);
                if (format != null) return format;
                formats.put(original, format = new VertexFormat(original));
                format.addElement(DefaultVertexFormats.COLOR_4UB);
                return format;
            }

            @Override
            public float[][][] remap(VertexFormat original, float[][][] data) {

                VertexFormat format = getNewFormat(original);
                int posIndex = 0, colorIndex = 0;
                for (int i = 0; i < format.getElementCount(); i++) {
                    if (format.getElement(i).isPositionElement()) posIndex = i;
                    if (format.getElement(i).getUsage() == EnumUsage.COLOR) colorIndex = i;
                }
                Vector3f a = new Vector3f(data[0][posIndex][0], data[0][posIndex][1], data[0][posIndex][2]);
                Vector3f b = new Vector3f(data[1][posIndex][0], data[1][posIndex][1], data[1][posIndex][2]);
                Vector3f c = new Vector3f(data[2][posIndex][0], data[2][posIndex][1], data[2][posIndex][2]);
                a.sub(b);
                c.sub(b);
                b.cross(c, a);
                b.normalize();
                float brightness = getBrightness(b);
                for (int i = 0; i < 4; i++) {
                    data[i][colorIndex][0] = brightness;
                    data[i][colorIndex][1] = brightness;
                    data[i][colorIndex][2] = brightness;
                }

                return data;
            }

            private float getBrightness(Vector3f normal) {

                float x = getFaceBrightness(EnumFacing.getFacingFromVector(normal.x, 0, 0));
                float y = getFaceBrightness(EnumFacing.getFacingFromVector(0, normal.y, 0));
                float z = getFaceBrightness(EnumFacing.getFacingFromVector(0, 0, normal.z));
                return x * normal.x * normal.x + y * normal.y * normal.y + z * normal.z * normal.z;
            }

            private float getFaceBrightness(EnumFacing facing) {

                switch (facing) {
                    case DOWN:
                        return 0.5F;
                    case UP:
                        return 1.0F;
                    case NORTH:
                    case SOUTH:
                        return 0.8F;
                    case WEST:
                    case EAST:
                        return 0.6F;
                    default:
                        return 1.0F;
                }
            }

        };

        public VertexFormat getNewFormat(VertexFormat original);

        public float[][][] remap(VertexFormat original, float[][][] data);

    }

    private static final class TransformedModel implements IBakedModel, IFlexibleBakedModel {

        private final IBakedModel parent;
        private final List<BakedQuad>[] quads;
        private final VertexFormat format;

        public TransformedModel(IBakedModel parent, List<BakedQuad>[] quads, VertexFormat format) {

            this.parent = parent;
            this.quads = quads;
            this.format = format;
        }

        @Override
        public List<BakedQuad> getFaceQuads(EnumFacing facing) {

            return quads[facing.ordinal()];
        }

        @Override
        public List<BakedQuad> getGeneralQuads() {

            return quads[6];
        }

        @Override
        public boolean isAmbientOcclusion() {

            return parent.isAmbientOcclusion();
        }

        @Override
        public boolean isGui3d() {

            return parent.isGui3d();
        }

        @Override
        public boolean isBuiltInRenderer() {

            return parent.isBuiltInRenderer();
        }

        @Override
        public TextureAtlasSprite getParticleTexture() {

            return parent.getParticleTexture();
        }

        @Override
        public ItemCameraTransforms getItemCameraTransforms() {

            return parent.getItemCameraTransforms();
        }

        @Override
        public VertexFormat getFormat() {

            return format;
        }

    }

}