/*
 * LIMITED USE SOFTWARE LICENSE AGREEMENT
 * This Limited Use Software License Agreement (the "Agreement") is a legal agreement between you, the end-user, and the FlatstoneTech Team ("FlatstoneTech"). By downloading or purchasing the software material, which includes source code (the "Source Code"), artwork data, music and software tools (collectively, the "Software"), you are agreeing to be bound by the terms of this Agreement. If you do not agree to the terms of this Agreement, promptly destroy the Software you may have downloaded or copied.
 * FlatstoneTech SOFTWARE LICENSE
 * 1. Grant of License. FlatstoneTech grants to you the right to use the Software. You have no ownership or proprietary rights in or to the Software, or the Trademark. For purposes of this section, "use" means loading the Software into RAM, as well as installation on a hard disk or other storage device. The Software, together with any archive copy thereof, shall be destroyed when no longer used in accordance with this Agreement, or when the right to use the Software is terminated. You agree that the Software will not be shipped, transferred or exported into any country in violation of the U.S. Export Administration Act (or any other law governing such matters) and that you will not utilize, in any other manner, the Software in violation of any applicable law.
 * 2. Permitted Uses. For educational purposes only, you, the end-user, may use portions of the Source Code, such as particular routines, to develop your own software, but may not duplicate the Source Code, except as noted in paragraph 4. The limited right referenced in the preceding sentence is hereinafter referred to as "Educational Use." By so exercising the Educational Use right you shall not obtain any ownership, copyright, proprietary or other interest in or to the Source Code, or any portion of the Source Code. You may dispose of your own software in your sole discretion. With the exception of the Educational Use right, you may not otherwise use the Software, or an portion of the Software, which includes the Source Code, for commercial gain.
 * 3. Prohibited Uses: Under no circumstances shall you, the end-user, be permitted, allowed or authorized to commercially exploit the Software. Neither you nor anyone at your direction shall do any of the following acts with regard to the Software, or any portion thereof:
 *  * Rent;
 *  * Sell;
 *  * Lease;
 *  * Offer on a pay-per-play basis;
 *  * Distribute for money or any other consideration; or
 *  * In any other manner and through any medium whatsoever commercially exploit or use for any commercial purpose.
 *  * Notwithstanding the foregoing prohibitions, you may commercially exploit the software you develop by exercising the Educational Use right, referenced in paragraph 2. hereinabove.
 *  4. Copyright. The Software and all copyrights related thereto (including all characters and other images generated by the Software or depicted in the Software) are owned by FlatstoneTech and is protected by United States copyright laws and international treaty provisions. FlatstoneTech shall retain exclusive ownership and copyright in and to the Software and all portions of the Software and you shall have no ownership or other proprietary interest in such materials. You must treat the Software like any other copyrighted material. You may not otherwise reproduce, copy or disclose to others, in whole or in any part, the Software. You may not copy the written materials accompanying the Software. You agree to use your best efforts to see that any user of the Software licensed hereunder complies with this Agreement.
 *  5. NO WARRANTIES. FLATSTONETECH DISCLAIMS ALL WARRANTIES, BOTH EXPRESS IMPLIED, INCLUDING BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE WITH RESPECT TO THE SOFTWARE. THIS LIMITED WARRANTY GIVES YOU SPECIFIC LEGAL RIGHTS. YOU MAY HAVE OTHER RIGHTS WHICH VARY FROM JURISDICTION TO JURISDICTION. FlatstoneTech DOES NOT WARRANT THAT THE OPERATION OF THE SOFTWARE WILL BE UNINTERRUPTED, ERROR FREE OR MEET YOUR SPECIFIC REQUIREMENTS. THE WARRANTY SET FORTH ABOVE IS IN LIEU OF ALL OTHER EXPRESS WARRANTIES WHETHER ORAL OR WRITTEN. THE AGENTS, EMPLOYEES, DISTRIBUTORS, AND DEALERS OF FlatstoneTech ARE NOT AUTHORIZED TO MAKE MODIFICATIONS TO THIS WARRANTY, OR ADDITIONAL WARRANTIES ON BEHALF OF FlatstoneTech.
 *  Exclusive Remedies. The Software is being offered to you free of any charge. You agree that you have no remedy against FlatstoneTech, its affiliates, contractors, suppliers, and agents for loss or damage caused by any defect or failure in the Software regardless of the form of action, whether in contract, tort, includinegligence, strict liability or otherwise, with regard to the Software. Copyright and other proprietary matters will be governed by United States laws and international treaties. IN ANY CASE, FlatstoneTech SHALL NOT BE LIABLE FOR LOSS OF DATA, LOSS OF PROFITS, LOST SAVINGS, SPECIAL, INCIDENTAL, CONSEQUENTIAL, INDIRECT OR OTHER SIMILAR DAMAGES ARISING FROM BREACH OF WARRANTY, BREACH OF CONTRACT, NEGLIGENCE, OR OTHER LEGAL THEORY EVEN IF FLATSTONETECH OR ITS AGENT HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES, OR FOR ANY CLAIM BY ANY OTHER PARTY. Some jurisdictions do not allow the exclusion or limitation of incidental or consequential damages, so the above limitation or exclusion may not apply to you.
 */

package tech.flatstone.appliedlogistics.common.tileentities.machines;

import net.minecraft.init.Blocks;
import net.minecraft.inventory.IInventory;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraft.item.crafting.FurnaceRecipes;
import net.minecraft.nbt.NBTTagCompound;
import net.minecraft.util.EnumFacing;
import net.minecraft.util.ITickable;
import tech.flatstone.appliedlogistics.common.items.Items;
import tech.flatstone.appliedlogistics.common.tileentities.TileEntityMachineBase;
import tech.flatstone.appliedlogistics.common.tileentities.inventory.InternalInventory;
import tech.flatstone.appliedlogistics.common.tileentities.inventory.InventoryOperation;
import tech.flatstone.appliedlogistics.common.util.EnumOres;
import tech.flatstone.appliedlogistics.common.util.InventoryHelper;

public class TileEntityFurnace extends TileEntityMachineBase implements ITickable {
    public static final float HIGHEST_MAX_TEMP = 380;
    public static final float LOWEST_MAX_TEMP = 23;

    private InternalInventory inventory = new InternalInventory(this, 100);


    private int fuelRemaining = 0;
    private int fuelTotal = 0;
    private double intTemperature = 0;
    private int fuelTempTick = 0;
    private int furnaceRows = 1;
    private boolean upgradeExtraSlots = false;
    private int[] smeltProgress = new int[9];
    private int maxProcessItems = 1;
    private Item lastFuelType;
    private int lastFuelValue;

    @Override
    public void markForUpdate() {
        super.markForUpdate();

        this.markForLightUpdate();
    }

    @Override
    public boolean canBeRotated() {
        return true;
    }

    @Override
    public ItemStack removeStackFromSlot(int index) {
        return null;
    }

    @Override
    public void initMachineData() {
        super.initMachineData();

        int furnaceCount = 1;
        int gearCount = 0;

        NBTTagCompound machineItemData = this.getMachineItemData();
        if (machineItemData != null) {
            for (int i = 0; i < 27; i++) {
                if (machineItemData.hasKey("item_" + i)) {
                    ItemStack item = new ItemStack(machineItemData.getCompoundTag("item_" + i));

                    if (ItemStack.areItemsEqual(item, Items.ITEM_MATERIAL_GEAR.getStack(1, EnumOres.IRON.getMeta())))
                        gearCount = item.getCount();

                    if (ItemStack.areItemsEqual(item, new ItemStack(Blocks.FURNACE)))
                        furnaceCount = item.getCount();

                    if (ItemStack.areItemsEqual(item, new ItemStack(Blocks.CHEST)))
                        upgradeExtraSlots = true;
                }
            }
        }

        furnaceCount--;
        if (furnaceCount == 1 && gearCount == 1)
            furnaceRows = 2;
    }

    @Override
    public void update() {
        if (fuelRemaining == 0 && inventory.getStackInSlot(0) != null && net.minecraft.tileentity.TileEntityFurnace.getItemBurnTime(inventory.getStackInSlot(0)) > 0) {
            if (inventory.getStackInSlot(0).getItem() == lastFuelType) {
                fuelRemaining = lastFuelValue;
            } else {
                fuelRemaining = net.minecraft.tileentity.TileEntityFurnace.getItemBurnTime(inventory.getStackInSlot(0));
                lastFuelType = inventory.getStackInSlot(0).getItem();
                lastFuelValue = fuelRemaining;
            }
            fuelTotal = fuelRemaining;
            inventory.decrStackSize(0, 1);
            this.markDirty();
            this.markForUpdate();
        }

        if (fuelRemaining > 0) {
            --fuelRemaining;
        }

        if (intTemperature < this.getMaxTemp() && fuelRemaining > 0) {
            fuelTempTick++;
        }

        if (fuelRemaining == 0 && fuelTempTick > 0) {
            fuelTempTick -= 0.2;
            fuelTotal = 0;

            if (fuelTempTick <= 0) {
                fuelTempTick = 0;

                this.markDirty();
                this.markForUpdate();
            }
        }

        intTemperature = (Math.sqrt(fuelTempTick) * 10);

        for (int i = 0; i < furnaceRows; i++) {
            // Check inputs for item, then move to process slot
            ItemStack processItem = inventory.getStackInSlot(i * 7 + 3);
            if (processItem == null) {
                smeltProgress[i] = 0;

                ItemStack input1 = inventory.getStackInSlot(i * 7 + 1);
                ItemStack input2 = inventory.getStackInSlot(i * 7 + 2);

                if (input1 == null && input2 == null)
                    continue;

                if (ItemStack.areItemsEqual(input1, input2)) {
                    // todo: have it pull multiple items from both slots if not enough in slot 1
                }

                if (input1 == null) {
                    inventory.setInventorySlotContents(i * 7 + 3, inventory.decrStackSize(i * 7 + 2, maxProcessItems));
                    this.markForUpdate();
                    this.markDirty();
                } else {
                    inventory.setInventorySlotContents(i * 7 + 3, inventory.decrStackSize(i * 7 + 1, maxProcessItems));
                    this.markForUpdate();
                    this.markDirty();
                }
            }

            // Checking to process items
            if (processItem != null && getMultiplier() > 0) {
                smeltProgress[i] += getMultiplier();

                if (smeltProgress[i] > 300) {
                    smeltProgress[i] = 300;
                    if (FurnaceRecipes.instance().getSmeltingResult(processItem.copy()) == null)
                        continue;
                    ItemStack outputStack = FurnaceRecipes.instance().getSmeltingResult(processItem.copy()).copy();
                    outputStack.setCount(processItem.getCount() * outputStack.getCount());
                    int slotsToCheck = upgradeExtraSlots ? 4 : 1;
                    int slotMin = i * 7 + 3 + 1;
                    int slotMax = i * 7 + 3 + slotsToCheck;
                    if (InventoryHelper.addItemStackToInventory(outputStack, inventory, slotMin, slotMax, true) == null) {
                        InventoryHelper.addItemStackToInventory(outputStack, inventory, slotMin, slotMax);
                        inventory.setInventorySlotContents(i * 7 + 3, null);
                        this.markForUpdate();
                        this.markDirty();
                    }
                }
            } else {
                if (smeltProgress[i] > 0)
                    smeltProgress[i]--;
            }
        }
    }

    public int getIntTemperature() {
        return (int) intTemperature;
    }

    public int getMultiplier() {
        int speed = (int) Math.floor((intTemperature - 100) / 100);
        if (speed < 0) speed = 0;
        return speed;
    }

    public int getMaxTemp() {
        return 200;
    }

    public int getFurnaceRows() {
        return furnaceRows;
    }

    public boolean isUpgradeExtraSlots() {
        return upgradeExtraSlots;
    }

    public int getFuelOffset() {
        return Math.round(((((float) fuelRemaining) / (float) fuelTotal)) * 100);
    }

    public int getSmeltProgress(int row) {
        return Math.round(((float) smeltProgress[row] / (float) 300) * 100);
    }

    private boolean canSmelt(ItemStack stack) {
        ItemStack itemstack = FurnaceRecipes.instance().getSmeltingResult(stack);
        return itemstack != null;
    }

//    @Override
//    public List<String> getWailaBodyToolTip(ItemStack itemStack, List<String> currentTip, IWailaDataAccessor accessor, IWailaConfigHandler config) {
//        return currentTip;
//    }

    @Override
    public IInventory getInternalInventory() {
        return inventory;
    }

    @Override
    public void onChangeInventory(IInventory inv, int slot, InventoryOperation operation, ItemStack removed, ItemStack added) {

    }

    @Override
    public int[] getAccessibleSlotsBySide(EnumFacing side) {
        return new int[0];
    }

    @Override
    public void readFromNBT(NBTTagCompound nbtTagCompound) {
        super.readFromNBT(nbtTagCompound);

        fuelRemaining = nbtTagCompound.getInteger("fuelRemaining");
        intTemperature = nbtTagCompound.getDouble("intTemperature");
        fuelTempTick = nbtTagCompound.getInteger("fuelTickTemp");
        fuelTotal = nbtTagCompound.getInteger("fuelTotal");
        furnaceRows = nbtTagCompound.getInteger("furnaceRows");
        upgradeExtraSlots = nbtTagCompound.getBoolean("upgradeExtraSlots");
        smeltProgress = nbtTagCompound.getIntArray("smeltProgress");
        maxProcessItems = nbtTagCompound.getInteger("maxProcessItems");
    }

    @Override
    public NBTTagCompound writeToNBT(NBTTagCompound nbtTagCompound) {
        super.writeToNBT(nbtTagCompound);

        nbtTagCompound.setInteger("fuelRemaining", fuelRemaining);
        nbtTagCompound.setDouble("intTemperature", intTemperature);
        nbtTagCompound.setInteger("fuelTickTemp", fuelTempTick);
        nbtTagCompound.setInteger("fuelTotal", fuelTotal);
        nbtTagCompound.setInteger("furnaceRows", furnaceRows);
        nbtTagCompound.setBoolean("upgradeExtraSlots", upgradeExtraSlots);
        nbtTagCompound.setIntArray("smeltProgress", smeltProgress);
        nbtTagCompound.setInteger("maxProcessItems", maxProcessItems);

        return nbtTagCompound;
    }

    /**
     * Furnace Notes:
     *
     * Goals:
     * > multiple inputs
     * > multiple processing
     * > increased production
     * > Auto Eject (upgrade card)
     * > Auto Insert (upgrade card)
     * > Storage Block (Compressor? or piston)
     * > Additional output Storage (Chest)
     *
     * Stone Age:
     * > Multiple Inputs: min 1, max 2
     * > Multiple Processing: min 1, max 2
     * > Increased productivity: +20%
     * > Additional Output Slots: Chest (double the slots)
     */

    /**
     * Additional Furnace Notes:
     *
     * Stone Furnace:
     * Base Max Temp: 120C
     * Max Temp: 120C
     * Base Input Slots: 1
     * Base Output Slots: 2
     * Max Input Slots: 1
     * Max Output Slots: 4
     * Base Furnaces: 1
     * Max Furnaces: 2
     * Max Speed: 1x
     *
     * Bronze Furnace:
     * Base Max Temp: 160C
     * Max Temp: 200C
     * Base Input Slots: 2
     * Base Output Slots: 2
     * Max Input Slots: 2
     * Max Output Slots: 4
     * Base Furnaces: 1
     * Max Furnaces: 2
     * Max Speed: 2x
     *
     * Mechanical Furnace:
     * Base Max Temp: 240C
     * Max Temp: 300C
     * Base Input Slots: 2
     * Base Output Slots: 2
     * Max Input Slots: 2
     * Max Output Slots: 4
     * Base Furnaces: 1
     * Max Furnaces: 3
     * Max Speed: 4x
     *
     * Industrial / Digital Furnace:
     * Base Max Temp: 300C
     * Max Temp: 380C
     * Base Input Slots: 2
     * Base Output Slots: 2
     * Max Input Slots: 2
     * Max Output Slots: 4
     * Base Furnaces: 1
     * Max Furnaces: 4
     * Max Speed: 8x
     */
}
